language: java
jdk: oraclejdk8
sudo: false


cache:
  directories:
  - ~/.gradle

before_install: chmod +x gradlew
install: ./gradlew assemble
script:
  - ./gradlew check
  - rm ~/.gradle/caches/modules-2/modules-2.lock
